config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/", to: "under_construction#index"
  get "landing", to: "landing#index"
  get "home", to: "homepage#index"

  get "/projects/:project" => "projects#show"

  get 'terms-of-service', to: 'static_pages#terms_of_service'
  get 'privacy-policy', to: 'static_pages#privacy_policy'

  scope '(:locale)', locale: /en|pl/ do
    root "homepage#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Locales
end

app/controllers/concerns/locales.rb
# frozen_string_literal: true

module Locales
  extend ActiveSupport::Concern

  included do
    before_action :set_locale
  end

  def set_locale
    cookies.permanent[:locale] = params[:locale] if params[:lc].present?
    # set locale to en always
    domain_locale = request.domain == :en
    I18n.locale = cookies.permanent[:locale] || params[:locale] || domain_locale || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end

  def self.default_url_options(options = {})
    options.merge(locale: I18n.locale)
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index; end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    render
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    def show
        render template: "projects/#{params[:project]}"
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    layout 'application'
    
    def terms_of_service; end
  
    def privacy_policy; end
  end
  

app/controllers/under_construction_controller.rb
class UnderConstructionController < ApplicationController
  def index
    render layout: 'under_construction'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepage/_clients_opinion_section.slim
- i18n_scope = 'homepage'

section.clients.container.has-mt-72.has-mb-180 id="clients_opinion"
  h1.is-green-80.title.has-text-centered = t 'clients.header', scope: i18n_scope
  .container

    h2.has-text-centered.client-opinion style="font-wieght: light; line-height: 4rem"
      span.is-green-80 „
      span.is-italic = t 'clients.opinion', scope: i18n_scope
      span.is-green-80 “
    h3.is-size-3.has-text-centered.mt-5
      span.is-size-5.is-green-80.is-bold SmartLifeClinic

app/views/homepage/_contact_form.slim
- i18n_scope = 'homepage'

section.contact.has-mt-120.mt-6-touch id="contact"
  h1.title.has-text-centered.mb-6 = t 'contact.contact_us_with_nda', scope: i18n_scope
  .container
    .columns
      .column
        .columns
          .column.is-flex.is-justify-content-center
            figure.image
              = image_tag 'daiji.png', class: 'person is-rounded'
          .column
            h2.is-size-4.mb-4
              | Daiji Kimura
            p.mb-1
              | CEO & Product Owner
            p.mb-1
              | +48 693-896-717
            p.mb-1
              daiji.kimura@jalappeno.pl
        .columns
          .column
            p = t 'contact.paragraph_html', scope: i18n_scope
      .column
        input.mb-3.input[type="text" placeholder="Full name"]
        input.mb-3.input[type="email" placeholder="Email"]
        input.mb-3.input[type="tel" placeholder="Phone"]
        textarea.mb-3.textarea[placeholder="Message"]
        label.checkbox
          input[type="checkbox"]
            = t 'contact.i_need', scope: i18n_scope
          span.is-green-80.is-bold
            | NDA
          = t 'contact.first', scope: i18n_scope
        label.checkbox
          input[type="checkbox"]
          = t 'contact.personal_data', scope: i18n_scope
          span.is-green-80.is-bold
            = t 'contact.privacy_policy', scope: i18n_scope

app/views/homepage/_development_section.slim
- i18n_scope = 'homepage'

section.has-mt-120.has-mt-6-touch id="development"
  h1.title.has-text-centered.mb-6 = t 'team.meet_our_team', scope: i18n_scope
  .container
    .columns.columns--development
      .column
          figure.image
              = image_tag "daiji-rounded.png"
          p.is-size-6.is-black.has-text-weight-semibold.mt-3 = "Daiji Kimura"
          p.is-size-6.is-black.has-text-weight-medium = "CEO"
      .column
          figure.image
              = image_tag "ritwick-rounded.png"
          p.is-size-6.is-black.has-text-weight-semibold.mt-3 = "Ritwick Malhotra"
          p.is-size-6.is-black.has-text-weight-medium = "CTO"
      .column
          figure.image
              = image_tag "jules-rounded.png"
          p.is-size-6.is-black.has-text-weight-semibold.mt-3 = "Julia Kostrzewa"
          p.is-size-6.is-black.has-text-weight-medium = "Art Director"
      .column
          figure.image
              = image_tag "alan-rounded.png"
          p.is-size-6.is-black.has-text-weight-semibold.mt-3 = "Alan Pieczonka"
          p.is-size-6.is-black.has-text-weight-medium = "Front-end Developer"
      .column
          figure.image
              = image_tag "sourav-rounded.png"
          p.is-size-6.is-black.has-text-weight-semibold.mt-3 = "Sourav Goswami"
          p.is-size-6.is-black.has-text-weight-medium = "Back-end Developer"

app/views/homepage/_film_section.slim
section.film.container.has-mb-120 id="film"
 .film__section
    video[width="100%" height="240" controls poster="https://www.colorbook.io/imagecreator.php?hex=28DD8B&width=1920&height=1080&text=%201080x1920"]
        source[src="movie.mp4" type="video/mp4"]
            source[src="movie.ogg" type="video/ogg"]
            |  Your browser does not support the video tag.

app/views/homepage/_header_section.slim
- i18n_scope = 'homepage'

.chilli__background
  .chilli.chilli--first.rellax data-rellax-speed="5"
  .chilli.chilli--third.rellax data-rellax-speed="-4"
  .chilli.chilli--fourth.rellax data-rellax-speed="2"
  .chilli.chilli--fifth.rellax data-rellax-speed="-3"
.chilli__background
  .chilli.chilli--first.rellax data-rellax-speed="5"
  .chilli.chilli--third.rellax data-rellax-speed="-4"
  .chilli.chilli--fourth.rellax data-rellax-speed="2"
  .chilli.chilli--fifth.rellax data-rellax-speed="-3"
.chilli__background
  .chilli.chilli--fifth.rellax data-rellax-speed="-3"
.chilli__background
  .chilli.chilli--third.rellax data-rellax-speed="-4"
  .chilli.chilli--fourth.rellax data-rellax-speed="2"
  .chilli.chilli--fifth.rellax data-rellax-speed="-3"
.chilli__background
  .chilli.chilli--first.rellax data-rellax-speed="5"
  .chilli.chilli--second.rellax data-rellax-speed="5"
  .chilli.chilli--fourth.rellax data-rellax-speed="2"
  .chilli.chilli--fifth.rellax data-rellax-speed="-3"
.chilli__background
  .chilli.chilli--first.rellax data-rellax-speed="5"
  .chilli.chilli--second.rellax data-rellax-speed="5"
  .chilli.chilli--third.rellax data-rellax-speed="-4"
  .chilli.chilli--fourth.rellax data-rellax-speed="2"
  .chilli.chilli--fifth.rellax data-rellax-speed="-3"

section.hero.container id="hero"
  .hero__box
    h1.is-size-1.title.has-mt-36 = t('hero.tagline', scope: i18n_scope).html_safe
    h2.is-size-6-touch.has-mt-36.subtitle.has-text-centered = t 'hero.subtitle', scope: i18n_scope, style: "color: black;"
    .hero__button
      button.button.button-outline.has-mt-18 = t 'hero.book_meeting', scope: i18n_scope

app/views/homepage/_projects_section.slim
- i18n_scope = 'homepage'

section.projects.container id="projects"
 .projects__section
    h1.is-size-4-touch.title.is-green-90.has-text-centered.has-mb-60 = t 'projects.our_projects', scope: i18n_scope
.slideshow-container.has-mb-72-touch
  .mySlides.fade
    .numbertext 2 / 6
    a href="/projects/artandliving" target="_blank"
      img src="assets/projects_artandliving.png" style="width:70%; margin: 0 auto;" /
    .text = t 'projects.furniture_store', scope: i18n_scope 
  .mySlides.fade
    .numbertext 1 / 6
    a href="/projects/smartlifeclinic" target="_blank"
      img src="assets/projects_smartlifeclinic.png" style="width:70%; margin: 0 auto;" /
    .text = t 'projects.healthcare_clinic', scope: i18n_scope
  .mySlides.fade
    .numbertext 3 / 6
    a href="/projects/hempchamp" target="_blank"
      img src="assets/projects_hempchamp.png" style="width:70%; margin: 0 auto;" /
    .text = t 'projects.cbd_manufacturer', scope: i18n_scope
  .mySlides.fade
    .numbertext 4 / 6
    a href="/projects/kimuraglamping" target="_blank"
      img src="assets/projects_glamping.png" style="width:70%; margin: 0 auto;" /
    .text = t 'projects.glamping_business', scope: i18n_scope
  .mySlides.fade
    .numbertext 5 / 6
    a href="/projects/bhpartykuly" target="_blank"
      img src="assets/projects_bhp.png" style="width:70%; margin: 0 auto;" /
    .text = t 'projects.ohs_industry', scope: i18n_scope
  .mySlides.fade
    .numbertext 6 / 6
    a href="/projects/przyjaciolkaprzyjaciolki" target="_blank"
      img src="assets/projects_pp.png" style="width:70%; margin: 0 auto;" /
    .text = t 'projects.cosmetic_salon', scope: i18n_scope
  a.prev onclick="plusSlides(-1)"  ❮
  a.next onclick="plusSlides(1)"  ❯
br/
javascript:
   var slideIndex = 1;
   showSlides(slideIndex);

   // Next/previous controls
   function plusSlides(n) {
   showSlides(slideIndex += n);
   }

   // Thumbnail image controls
   function currentSlide(n) {
      showSlides(slideIndex = n);
   }

   function showSlides(n) {
   var i;
   var slides = document.getElementsByClassName("mySlides");
   var dots = document.getElementsByClassName("dot");
   if (n > slides.length) {slideIndex = 1}
   if (n < 1) {slideIndex = slides.length}
   for (i = 0; i < slides.length; i++) {
         slides[i].style.display = "none";
   }
   for (i = 0; i < dots.length; i++) {
         dots[i].className = dots[i].className.replace(" active", "");
   }
   slides[slideIndex-1].style.display = "block";
   dots[slideIndex-1].className += " active";
   }

app/views/homepage/_work_section.slim
- i18n_scope = 'homepage'

section.work.container id="how-we-work"
  .work__section
    h2.is-size-4-touch.title.has-text-centered = t 'work.visualize', scope: i18n_scope
    h3.subtitle.has-text-centered.has-pt-10.has-mb-120.has-mb-72-touch = t 'work.subtitle', scope: i18n_scope 
    .work__section__inside.has-mb-36-touch
      .columns.reverse-columns
        .column
          .step_frame
            = image_tag 'frame', class: 'frame appear-from-up'
            = image_tag 'image_1', class: 'frame-image appear-from-left rellax', 'data-rellax-speed': "1"
        .column
          .is-block.is-hidden-tablet
            = image_tag 'image_1_mobile', class: "margin-0-auto is-block is-hidden-tablet mb-4"
          .step__text
            .has-text-centered.is-hidden-tablet.is-flex.is-justify-content-center.is-align-items-center
              .step__number.is-inline-block.is-size-6-touch.mr-2 = t 'work.step_1.step', scope: i18n_scope
              .step__title.is-size-3.is-size-6-touch.is-inline-block = t 'work.step_1.meeting', scope: i18n_scope
            .step__number.has-pb-18.is-hidden-mobile = t 'work.step_1.step', scope: i18n_scope
            .step__title.is-size-3.is-size-4-touch.is-hidden-mobile = t 'work.step_1.meeting', scope: i18n_scope
            .step__content.mt-5
              p.is-black.mb-3 = t 'work.step_1.content.p1'.html_safe, scope: i18n_scope
              p.is-black.mb-3 = t 'work.step_1.content.p2'.html_safe, scope: i18n_scope
              p.is-black = t 'work.step_1.content.p3'.html_safe, scope: i18n_scope

    .work__section__inside.has-mb-36-touch
      .columns
        .column
          .is-block.is-hidden-tablet
            = image_tag 'image_2_mobile', class: "margin-0-auto is-block has-text-centered is-hidden-tablet mb-4"
          .step__text
            .has-text-centered.is-hidden-tablet.is-flex.is-justify-content-center.is-align-items-center
              .step__number.is-inline-block.is-size-6-touch.mr-2 = t 'work.step_2.step', scope: i18n_scope
              .step__title.is-size-3.is-size-6-touch.is-inline-block = t 'work.step_2.design', scope: i18n_scope
            .step__number.is-hidden-mobile = t 'work.step_2.step', scope: i18n_scope
            .step__title.is-size-3.is-size-4-touch.mt-5.is-hidden-mobile = t 'work.step_2.design', scope: i18n_scope
            .step__content.mt-5
              p.is-black = t 'work.step_2.content.p1', scope: i18n_scope
              .content
                ul
                  li = t 'work.step_2.content.points.p1', scope: i18n_scope
                  li = t 'work.step_2.content.points.p2', scope: i18n_scope
                  li = t 'work.step_2.content.points.p3', scope: i18n_scope
                  li = t 'work.step_2.content.points.p4', scope: i18n_scope

              p = t('work.step_2.content.p2', scope: i18n_scope).html_safe
              p
                b = t('work.step_2.content.p3', scope: i18n_scope).html_safe
        .column
          .step_frame
            = image_tag 'frame', class: 'frame appear-from-up'
            = image_tag 'image_2', class: 'frame-image appear-from-right'

    .work__section__inside.spacer.has-mb-36-touch
      .columns.reverse-columns
        .column
          .step_frame
            = image_tag 'frame', class: 'frame appear-from-up'
            = image_tag 'image_3', class: 'frame-image appear-from-left'

        .column
          .is-block.is-hidden-tablet
            = image_tag 'image_3_mobile', class: "margin-0-auto is-block has-text-centered is-hidden-tablet mb-4"
          .step__text
            .has-text-centered.is-hidden-tablet.is-flex.is-justify-content-center.is-align-items-center
              .step__number.is-inline-block.is-size-6-touch.mr-2 = t 'work.step_3.step', scope: i18n_scope
              .step__title.is-size-3.is-size-5-touch.is-size-6-touch.is-inline-block = t 'work.step_3.research', scope: i18n_scope
            .step__number.is-hidden-mobile = t 'work.step_3.step', scope: i18n_scope
            .step__title.is-size-3.is-size-4-touch.mt-5.is-lowercase.is-hidden-mobile = t 'work.step_3.research', scope: i18n_scope
            .step__content.mt-5
              p.is-black.mb-3 = t 'work.step_3.content.p1', scope: i18n_scope
              p.is-black.mb-3 = t 'work.step_3.content.p2', scope: i18n_scope
              p.is-black = t 'work.step_3.content.p3', scope: i18n_scope

    .work__section__inside.has-mb-36-touch
      .columns
        .column
          .is-block.is-hidden-tablet
            = image_tag 'image_4_mobile', class: "margin-0-auto is-block has-text-centered is-hidden-tablet mb-4"
          .step__text
            .has-text-centered.is-hidden-tablet.is-flex.is-justify-content-center.is-align-items-center
              .step__number.is-inline-block.is-size-6-touch.mr-2 = t 'work.step_4.step', scope: i18n_scope
              .step__title.is-size-3.is-size-6-touch.is-inline-block = t 'work.step_4.maintaince', scope: i18n_scope
            .step__number.is-hidden-mobile = t 'work.step_4.step', scope: i18n_scope
            .step__title.is-size-3.is-size-4-touch.mt-5.is-hidden-mobile = t 'work.step_4.maintaince', scope: i18n_scope
            .step__content.mt-5
              p.is-black = t 'work.step_4.content.p1', scope: i18n_scope
        .column
          .step_frame
            = image_tag 'frame', class: 'frame appear-from-up'
            = image_tag 'image_4', class: 'frame-image appear-from-right'

app/views/homepage/index.slim
- i18n_scope = 'homepage'

= render 'homepage/header_section'
= render 'homepage/film_section'
= render 'homepage/work_section'
= render 'homepage/projects_section'
= render 'homepage/development_section'
= render 'homepage/contact_form'
= render 'homepage/clients_opinion_section'

.touch-disable
  = javascript_pack_tag 'parallax', 'data-turbolinks-track': 'reload'

app/views/layouts/_analytics_tag.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-185847618-1">
</script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-185847618-1');
</script>

app/views/layouts/_cookie_notice.slim
#cookie-container.appear-from-down
  .grid
    .left
      = image_tag 'cookie', width: '30px', height: '30px'
    .center
      p
        | We use cookies. By continuing to browse the site you are agreeing to our&nbsp;
        = link_to 'Privacy Policy', privacy_policy_path, class: 'is-green-80 is-bold'
    .right
      #close-cookie
        = image_tag 'cross', width: '12px', height: '12px'

= javascript_pack_tag 'cookie_notice'

app/views/layouts/_footer.slim
- i18n_scope = 'footer'

footer
  .container
    .columns.has-text-centered.is-mobile.is-multiline
      .column.is-half-mobile.has-text-left
        h1.subtitle.footer__subtitle.has-mb-60 = t 'design', scope: i18n_scope
        .footer__link
          a href="#" Project UX
        .footer__link
          a href="#" Project UI
        .footer__link
          a href="#" Figma
        .footer__link
          a href="#" Graphics
        .footer__link
          a href="#" Projects
        .footer__link
          a href="#" Products
      .column.is-half-mobile.has-text-left
        h1.subtitle.footer__subtitle.has-mb-60 = t 'development', scope: i18n_scope 
        .footer__link
          a href="#" Ruby On Rails
        .footer__link
          a href="#" React
        .footer__link
          a href="#" ECommerce
        .footer__link
          a href="#" React Native
        .footer__link
          a href="#" IOT
        .footer__link
          a href="#" Python
      .column.is-half-mobile.has-text-left
        h1.subtitle.footer__subtitle.has-mb-60 = t 'projects', scope: i18n_scope
        .footer__link
          a href="/projects/smartlifeclinic" Smartlife Clinic
        .footer__link
          a href="#" OMniS
        .footer__link
          a href="#" ECommerce
        .footer__link
          a href="/projects/artandliving" Art & Living
        .footer__link
          a href="#" Torn Trader
        .footer__link
          a href="/projects/bhpartykuly" BHP Artykuly
        .footer__link
          a href="/projects/kimuraglamping" Kimura Glamping
      .column.is-half-mobile.has-text-left
        h1.subtitle.footer__subtitle.has-mb-60 = t 'company', scope: i18n_scope
        .footer__link
          a href="#" Blog
        .footer__link
          a href="#" Privacy Policy
        .footer__link
          a href="#" Product
        .footer__link
          a href="/projects/artandliving" Art & Living
        .footer__link
          a href="#" Torn Trader
        .footer__link
          a href="/projects/bhpartykuly" BHP Artykuly
      .column.is-fullwidth-mobile.has-text-left.has-text-centered-mobile
        h1.subtitle.footer__subtitle.has-mb-60 = t 'contact', scope: i18n_scope
        .footer__link
          a href="mailto:hello@jalappeno.pl" hello@jalappeno.pl
        .footer__link
          a href="tel:+48693896717" +48 693 896 717
        .footer__link Jalappeno Sp. z o.o.
    .columns.has-text-centered
      .column.is-flex-desktop.is-justify-content-flex-start
        = image_tag "logo", alt: "jalappeno logo"
      .column.is-flex-desktop.is-justify-content-flex-end.is-justify-content-center-mobile.no-footer-margin-mobile
        a.m-2 href="https://github.com/"
          = image_tag 'github_icon.svg'
        a.m-2 href="https://www.behance.net/"
          = image_tag 'behance_icon.svg'
        a.m-2 href="https://pl.linkedin.com/"
          = image_tag 'linkedin_icon.svg'
        a.m-2 href="https://www.facebook.com/"
          = image_tag 'facebook_icon.svg'
        a.m-2 href="https://www.instagram.com/"
          = image_tag 'instagram_icon.svg'
        a.m-2 href="https://dribbble.com/"
          = image_tag 'dribble_icon.svg'

app/views/layouts/_loader.html.erb
<div id="loader" style="z-index: 10000; position: fixed;
    background-color: #fff; height: 100%; width: 100%;
    top: 0; left: 0; display: inline-flex; flex-direction: column;
    align-items: center; justify-content: center;overflow:hidden">
  <div id="loader-image" style="width: 14vmin; animation: fade-in-out 2s linear infinite">
    <picture>
      <source srcset="<%= image_url 'loader.webp' %>" type="image/webp">
      <source srcset="<%= image_url 'loader.png' %>" type="image/png">
      <%= image_tag 'loader.webp', style: "width: 14vmin" %>
    </picture>
  </div>

  <div id="text-container" style="margin-top: 4.5vmin">
    <span id="loader-text" style="font-size: 4vmin;min-height: 4vmin;display: inline;font-weight: 600">
      Loading...
    </span>
    <span id="cursor" style="font-size: 4vmin;min-height: 4vmin;display: inline;">
      |
    </span>
  </div>

  <div id="arrowDown" style="width: 3vmin;position: absolute;bottom: 2vmin;animation: fade-in-out 1s ease infinite">
    <%= image_tag 'arrow-down.svg', style: 'width: 3vmin' %>
  </div>
</div>

<script>
  const loaderContainer = document.getElementById('loader')
  const loaderText = document.getElementById('loader-text')
  const chars = loaderText.innerText.split('')
  const cursor = document.getElementById('cursor')
  const dismiss = document.getElementById('arrowDown')
  const len = chars.length
  const dismissTimeMS = 1000

  let index = 0
  let time = Date.now()

  loaderText.innerText = ''

  setInterval(function() {
    if (index == len) {
      if (loaderText.innerText === '') {
        index = 0
      } else {
        if (Date.now() - time > 3000) {
          loaderText.innerText = loaderText.innerText.split('').slice(0, -1).join('')
          cursor.style.animation = 'none'
        } else {
          cursor.style.animation = 'blink 0.5s ease infinite'
        }
      }
    } else {
      loaderText.innerText += chars[index++]
      time = Date.now()
    }
  }, 125)

  dismissLoader = () => {
    if (loaderContainer)
      loaderContainer.style.animation = `hide ${dismissTimeMS}ms ease forwards`

    setTimeout(() => document.body.removeChild(loaderContainer), dismissTimeMS + 100)
  }

  // document.addEventListener('DOMContentLoaded', () => {
  //   dismissLoader()
  // })

  dismiss.onclick = () => { dismissLoader() }
  window.onload = () => { dismissLoader() }
</script>

app/views/layouts/_meta_tags.slim
meta charset="utf-8"
meta name="description" content="#{t 'metatags.author'}"
meta name="author" content="#{t 'metatags.author'}"
meta name="keywords" lang="#{ I18n.locale }" content="#{t 'metatags.keywords' }"
meta name="title" content="#{t 'metatags.title'}"
meta property="og:description" content="#{t 'metatags.author'}"
meta property="og:title" content="#{t 'metatags.title'}"
meta property="og:type" content="website"
meta property="og:url" content="#{request.original_url}"
meta name="robots" content="all"
meta name="revisit-after" content="3days"
meta name="viewport" content="width=device-width,initial-scale=1"
meta property="og:image" itemprop="image" content=("#{image_url 'favicons/og-256.png' }")

app/views/layouts/_navbar.slim
nav.container-fluid.navbar.is-fixed-top.p-3 role="navigation" aria-label="main navigation"
  .navbar-brand
    a.navbar-item.is-hidden-desktop.button.is-primary href="tel:+48713333222"
      = "call now"
    a.navbar-item.navbar-item__logo href="/"
      = image_tag "logo", alt: "jalappeno logo"

    a.navbar-burger.burger role="button" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample"
      span.is-green-100 aria-hidden="true"
      span.is-green-100 aria-hidden="true"
      span.is-green-100 aria-hidden="true"

  .navbar-menu id="navbarBasicExample"
    .navbar-start

    .navbar-end.max-width-500px
      a.navbar-item.is-size-4-touch = t('navbar.about_us')
      a.navbar-item.is-size-4-touch href="#development"
        = t('navbar.team')
      a.navbar-item.is-size-4-touch href="#projects"
        = t('navbar.clients')
      a.navbar-item.is-size-4-touch = t('navbar.blog')
      a.navbar-item.is-hidden-desktop.navbar-end__call-now.is-size-4-touch href="tel:+48713333222"
        = "call now"

      .navbar-item.is-hidden-touch
        .buttons
          a.button.is-primary href="tel:+48693896717"
            = "call now"

app/views/layouts/_navbar_landing.slim
nav.navbar.is-fixed-top role="navigation" aria-label="main navigation"
  .navbar-brand.is-flex-touch.is-justify-content-center.landing__navbar__logo
    a.button.button-shadowed.is-primary.under-construction__contact.is-hidden-tablet href="tel:+48693896717"
      strong.is-white.is-lowercase.has-text-weight-light = "call now"
    a.button.button-fill-hover.button-shadowed.under-construction__contact.is-hidden-tablet.mr-3.ml-3 href="tel:+48693896717" style="color: #28dd8b; border-color: #28dd8b;"
      span.has-text-weight-light book meeting
    = image_tag "logo"

  .navbar-menu
    .navbar-star

    .navbar-end.is-justify-content-flex-end
      .navbar-item.pr-6
        .buttons
          a.button.button-shadowed.is-primary.under-construction__contact href="tel:+48693896717"
            strong.is-white.is-lowercase.has-text-weight-light = "call us"
            /TODO: When the app is ready, replace the #book-meeting with #{request.base_url}/#book-meeting
          a.button.button-fill-hover.button-shadowed.under-construction__contact href="#book-meeting" style="color: #28dd8b; border-color: #28dd8b;"
            strong.is-lowercase.has-text-weight-light = "book meeting"

app/views/layouts/_navbar_underconstruction.slim
nav.navbar.is-fixed-top role="navigation" aria-label="main navigation"
  .navbar-brand.is-flex-touch.is-justify-content-center	
    a.navbar-item.pl-6 href="/"
      = image_tag "logo"

  .navbar-menu
    .navbar-star

    .navbar-end.is-justify-content-flex-end
      .navbar-item.pr-6
        .buttons
          a.button.is-primary.under-construction__contact href="tel:+48693896717"
            strong.is-white.is-lowercase.has-text-weight-light = t('navbar.call_now')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="has-navbar-fixed-top" lang="<%= I18n.locale %>">
  <head>
    <title>Jalappeno</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'storefront', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= render 'layouts/analytics_tag' %>
  </body>
</html>